backend:
  name: github
  repo: bright/new-www
  branch: gatsby
  base_url: https://github-auth.brightinventions.pl
publish_mode: editorial_workflow
site_url: https://brightinventions.pl/
logo_url: https://brightinventions.pl/images/logo.png
media_folder: '/static/images'
public_folder: '/images'
collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front IllegalAccessExceptionmatter
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'members',
          searchFields: ['name'],
          valueField: 'author_id',
          displayFields: ['name', 'author_id'],
        }
      - {
          label: 'SecondAuthor',
          name: 'secondAuthor',
          widget: 'relation',
          collection: 'members',
          searchFields: ['name'],
          valueField: 'author_id',
          displayFields: ['name', 'author_id'],
          required: false,
        }
      - {
          label: 'ThirdAuthor',
          name: 'thirdAuthor',
          widget: 'relation',
          collection: 'members',
          searchFields: ['name'],
          valueField: 'author_id',
          displayFields: ['name', 'author_id'],
          required: false,
        }
      - { label: 'Tags', name: 'tags', widget: 'tags' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false }
      - { label: 'Comments', name: 'comments', widget: 'boolean', default: true }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true }
  - name: 'members' # Used in routes, e.g., /admin/collections/blog
    label: 'Members' # Used in the UI
    folder: 'content/members' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'member' }
      - { label: 'Author id', name: 'author_id', widget: 'string' }
      - { label: 'No longer with us', name: 'ex', widget: 'boolean', default: false }
      - { label: 'Slug', name: 'slug', widget: 'string', hint: 'URL path' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Short Name', name: 'short_name', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Website', name: 'web', widget: 'string', required: false }
      - { label: 'Avatar', name: 'avatar', widget: 'image', required: false }
      - { label: 'AvatarHover', name: 'avatar_hover', widget: 'image', required: false }
      - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
      - { label: 'Github', name: 'github', widget: 'string', required: false }
      - { label: 'Stack Overflow', name: 'stackoverflow', widget: 'string', required: false }
      - { label: 'Full description', name: 'body', widget: 'markdown' }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'list', allow_add: true, required: false }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true }
  - name: 'jobs' # Used in routes, e.g., /admin/collections/blog
    label: 'Jobs' # Used in the UI
    folder: 'content/jobs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'job' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'ImageJob', name: 'imagejob', widget: 'image' }
      - { label: 'Image-Alt-Job', name: 'image-alt-job', widget: string }
      - { label: 'Hours', name: 'hours', widget: 'string' }
      - { label: 'Salary', name: 'salary', widget: 'string' }
      - { label: 'Salary Min', name: 'salary_min', widget: 'number', required: false }
      - { label: 'Salary Max', name: 'salary_max', widget: 'number', required: false }
      - { label: 'Working Time', name: 'working time', widget: 'select', options: ['full time', 'part time'] }
      - {
          label: 'Technology',
          name: 'technology',
          widget: 'select',
          multiple: true,
          options:
            [
              'Android',
              'iOS',
              'Kotlin',
              'Blockchain',
              'Java',
              'Spring',
              'TypeScript',
              'React',
              'Angular',
              'Node.js',
              'NestJS',
              'MySQL',
              'PostgreSQL',
              'Swift',
              'AWS',
              'Bluetooth',
              'iBeaconIoT',
            ],
        }
      - {
          label: 'Show new title More About Us',
          name: 'show_new_title_more_about_us',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Links', name: 'links_more_about_us', widget: 'markdown' }
      - {
          label: 'Title Recruiter Info',
          name: 'title_recruiter_info',
          widget: 'string',
          hint: 'section recruiter info',
        }
      - { label: 'Name Recruiter', name: 'name_recruiter', widget: 'string', hint: 'section recruiter info' }
      - { label: 'Workplace Recruiter', name: 'workplace_recruiter', widget: 'string', hint: 'section recruiter info' }
      - { label: 'Image Recruiter Info', name: 'image_recruiter_info', widget: 'image', hint: 'section recruiter info' }
      - {
          label: 'Image Alt Recruiter Info',
          name: 'image_alt_recruiter_info',
          widget: string,
          hint: 'section recruiter info',
        }
      - {
          label: 'Button Instagram ',
          name: 'button_instagram',
          widget: 'string',
          hint: 'https://www.instagram.com/your_address/  -section recruiter info',
        }
      - { label: 'Button', name: 'button', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'list', allow_add: true, required: false }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          required: true,
          valueType: 'int',
          min: 1,
          step: 1,
          default: 1,
        }
      - { label: 'Recruting Process Image2 Title', name: 'recruting_image2_title', widget: 'string' }
      - { label: 'Recruting Process Image3 Title', name: 'recruting_image3_title', widget: 'string' }

  - name: 'projects' # Used in routes, e.g., /admin/collections/blog
    label: 'Projects' # Used in the UI
    folder: 'content/projects' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
      - { label: 'Project-id', name: 'project_id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          required: false,
          valueType: 'int',
          min: 1,
          step: 1,
          default: 99,
        }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'list', allow_add: true, required: false }
      - { label: 'Show on homepage', name: 'show on homepage', widget: 'boolean', default: false }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true }

  - name: 'our-areas' # Used in routes, e.g., /admin/collections/blog
    label: 'Our Service' # Used in the UI
    folder: 'content/our-areas' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - {
          label: 'TeamMembers',
          name: 'team_members',
          widget: 'relation',
          collection: 'members',
          searchFields: ['name'],
          valueField: 'author_id',
          displayFields: ['name', 'author_id'],
          multiple: true,
        }
      - {
          label: 'FAQs',
          name: 'faqs',
          widget: 'relation',
          collection: 'faqs',
          searchFields: ['name'],
          valueField: 'faqs_id',
          displayFields: ['name', 'faqs_id'],
          multiple: true,
        }
      - {
          label: 'Project',
          name: 'project',
          widget: 'relation',
          collection: 'projects',
          searchFields: ['name'],
          valueField: 'project_id',
          displayFields: ['name', 'project_id'],
          multiple: true,
        }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'our-service' }

      - {
          label: 'Meta title',
          name: 'meta_title',
          widget: 'text',
          pattern: ['^.{0,50}$', 'Must have no more than 50 characters'],
        }
      - {
          label: 'Meta description',
          name: 'meta_description',
          widget: 'text',
          pattern: ['^.{0,160}$', 'Must have no more than 160 characters'],
        }
      - { label: 'Our services icon', name: 'our_services_icon', widget: 'image' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string', hint: 'URL path' }
      - { label: 'Short Description', name: 'short_description', widget: 'markdown' }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          required: false,
          valueType: 'int',
          min: 1,
          step: 1,
          default: 1,
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Intro', name: 'intro', widget: 'string' }
      - { label: 'Image Our Service', name: 'image_our_service', widget: 'image' }
      - { label: 'Image Alt OurService', name: 'image_alt_our_service', widget: string }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Button', name: 'button', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Button2', name: 'button2', widget: 'string' }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true }
      - { label: 'Show case study', name: 'show_case_study', widget: 'boolean', default: true }
      - { label: 'Show technology stack', name: 'show_technology_stack', widget: 'boolean', default: true }
      - { label: 'Title Team', name: 'title_team', widget: 'string' }
      - { label: 'Title Case Study', name: 'title_case_study', widget: 'string' }
      - { label: 'Title FAQs', name: 'title_faqs', widget: 'string' }
      - { label: 'Title Contact', name: 'title_contact', widget: 'string' }
      - { label: 'Description Contact', name: 'description_contact', widget: 'markdown' }

  - name: 'faqs' # Used in routes, e.g., /admin/collections/blog
    label: 'FAQs' # Used in the UI
    folder: 'content/faqs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'faqs' }
      - { label: 'FAQs id', name: 'faqs_id', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string', hint: 'URL path' }
      - { label: 'Question', name: 'question', widget: 'markdown' }
      - { label: 'Answer', name: 'answer', widget: 'markdown' }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true }
