name: Publish website

on:
  push:
    branches:
      - gatsby
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        name: Yarn cache
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v29-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v29-
      - name: Gatsby Cache
        id: gatsby-cache-build
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-v29-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-v29-${{ github.ref_name }}
      - run: yarn install
      - run: yarn run build
        if: ${{ github.ref == 'refs/heads/gatsby' }}
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          CI: true
          GATSBY_ACTIVE_ENV: production
          GATSBY_CPU_COUNT: 1
      - run: yarn run build
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          CI: true
          DEPLOY_S3_BUCKET_NAME: 'brightinventions-pl-website-content-staging'
          GATSBY_ACTIVE_ENV: staging
          SITE_URL: 'https://staging.brightinventions.pl/'
          GATSBY_CPU_COUNT: 1
  deploy-s3:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        name: Yarn cache
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v29-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v29-
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-v29-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-v29-${{ github.ref_name }}
      - run: yarn install
      - run: yarn run deploy-s3
        if: ${{ github.ref == 'refs/heads/gatsby' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID }}
          GATSBY_ACTIVE_ENV: production
      - run: yarn run invalidate-cf-cache
        if: ${{ github.ref == 'refs/heads/gatsby' }}
        env:
          AWS_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID }}
      - run: yarn run deploy-s3
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}
          SITE_URL: 'https://staging.brightinventions.pl/'
          DEPLOY_S3_BUCKET_NAME: 'brightinventions-pl-website-content-staging'
          GATSBY_ACTIVE_ENV: staging
      - run: yarn run invalidate-cf-cache
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          AWS_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}

